name: second_work_flow # Workflow name

on:
  push:
    branches: [ "main" ]  # Trigger on main branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone the repository

      - name: Log in to Docker Hub using echo
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t amitkumar0441/nextjsapp:latest .
          docker tag amitkumar0441/nextjsapp:latest amitkumar0441/nextjsapp:${{ github.sha }}

      - name: Push to Docker Hub
        run: |
          docker push amitkumar0441/nextjsapp:latest
          docker push amitkumar0441/nextjsapp:${{ github.sha }}

 